version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - EXPIRES_IN=${EXPIRES_IN}
      - CLOUD_NAME=${CLOUD_NAME}
      - CLOUD_API_KEY=${CLOUD_API_KEY}
      - CLOUD_API_SECRET=${CLOUD_API_SECRET}
      - DATABASE_URL=${DATABASE_URL}
    restart: always
    container_name: tps_nest