apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: sample-app-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: node-app # Name of your deployment
  minReplicas: 5                # Minimum number of replicas
  maxReplicas: 10               # Maximum number of replicas
  metrics:
    - type: Resource
      resource:
        name: cpu               # Target metric (CPU usage)
        target:
          type: Utilization
          averageUtilization: 50 # Target CPU utilization percentage
    - type: Resource
      resource:
        name: memory            # Target metric (Memory usage)
        target:
          type: Utilization
          averageUtilization: 60 # Target Memory utilization percentage