apiVersion: v1
kind: Service
metadata:
  name: node-app
  labels:
    app: node-app
spec:
  type: LoadBalancer # Expose the app publicly (use ClusterIP for internal access only)
  ports:
  - port: 80          # External port
    targetPort: 8083  # Port inside the Pod
    protocol: TCP
  selector:
    app: node-app
