import { ApiProperty } from "@nestjs/swagger";

export class CreateUserDto {
   
    @ApiProperty()
    user_name: string;
    @ApiProperty()
    email: string;
    @ApiProperty()
    phone: string;
    @ApiProperty()
    password: string;
    @ApiProperty()
    address: string;
    @ApiProperty()
    city: string;
    @ApiProperty()
    state: string;
    @ApiProperty()
    zip: number;
    @ApiProperty()
    country: string;

    // rating?: number; // Optional, as it may not always be provided
    // avatar_url?: string;
    // user_role:string;
    // created_at?: Date; // Optional if it's generated by the database
    // updated_at?: Date; // Optional if it's generated by the database
    // isDeleted?: boolean; 
    }

  